name: ecommerce_app
description: Flutter eCommerce app (part of the Flutter & Firebase Masterclass)

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0
  equatable: 2.0.5
  flutter_staggered_grid_view: 0.7.0
  flutter_rating_bar: 4.0.1
  go_router: 14.6.0
  riverpod: 2.6.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  rxdart: 0.28.0
  sembast: 3.7.5+2
  sembast_web: 2.4.0+4
  path_provider: 2.1.5
  cached_network_image: 3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter    
  flutter_launcher_icons: 0.14.1
  build_runner: 2.4.13
  flutter_lints: 5.0.0
  custom_lint: 0.7.0
  riverpod_lint: 2.6.2
  mocktail: 1.0.4
  riverpod_generator: 2.6.2


# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/app-icon.png"  
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    # Used for Golden Image tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    # Add all product images
    - assets/products/

